name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v -o matchmaker.exe ./...

#     - name: Test
#       run: go test -v ./...

      - name: Uploading files
        uses: actions/upload-artifact@v2
        with:
          name: matchmaker
          path: |
            config/*
            matchmaker.exe

      - name: Zipping
        uses: papeloto/action-zip@v1
        with:
          files: config/ matchmaker.exe README.md
          recursive: false
          dest: matchmaker.zip

      - name: Create Artifact Folder
        run: New-Item -Path '${{ github.workspace }}' -Name "Releases" -ItemType "directory"
        shell: powershell

      - name: Copy ZIP
        run: Copy matchmaker.zip '${{ github.workspace }}/Releases'
        shell: powershell

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/Releases
          name: ${{ github.run_number }}

      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest_build
          message: automatic release on push to master
          files: matchmaker.zip

